### PR TITLE
Allow ENV Variables

### PR DESCRIPTION
**Pull request by A-Lawrence**
👋🏼  Howdy!

I had a need to utilise cumulus in CI/CD, and across multiple projects locally, so the single config value didn't quite work for that setup. I figured I'd contribute these changes back to you:

- Small tidy up in ensuring any references to the helpers class are from this package, rather than deferring to VaporHelpers.
- Loaded env variables at runtime
- Check $_ENV, then env(), and then the local config for the Cloudflare token.

### CODE REVIEW

**Comment by Orrison** [comment]
Howdy! This stuff looks great! Feel free to open again or another one if you would like me to take a look and possibly merge it in!

**Comment by A-Lawrence** [comment]
Opened the MR! I was just waiting to see a successful run where I wasn't tinkering with things, in GH Actions :)

CleanShot 2023-02-04 at 23 22 12

**Review by Orrison — COMMENTED** [review]
This is awesome! Thank you so much for this!

What would you think about the loading from `env` functionality being behind a flag? Something like `--token-from-env` or similar? I think it may be preferable for that to be explicit to make sure there is always a clear understanding of where the token is coming from.

**Comment by A-Lawrence** [comment]
I would be open to that idea, for sure!

The initial concept was based entirely on how Vapor defers to the environment variables before the user's config, so there's certainly precedent for it behaving in this way for people that are used to interacting with Vapor in CI/CD.

If venturing down the path of adding a flag to control it, I wonder if there's a way of also wrangling #2 into the mix so that you can _either_ load from the environment **or** use the token that was provided via the CLI?

**Comment by Orrison** [comment]
> I would be open to that idea, for sure!
> 
> The initial concept was based entirely on how Vapor defers to the environment variables before the user's config, so there's certainly precedent for it behaving in this way for people that are used to interacting with Vapor in CI/CD.
> 
> If venturing down the path of adding a flag to control it, I wonder if there's a way of also wrangling #2 into the mix so that you can _either_ load from the environment **or** use the token that was provided via the CLI?

Ah! That makes sense. Since there is a precedence with Vapor CLI I am fine with how it is.

I was planning to get to #2 sometime this month, but feel free if you were interested in tackling it. Though I do feel that this feature you just added does tackle the core issue of #2, running in CLI, in a much more secure way.

**Review by Orrison — APPROVED** [review]

**Pull request merged**
